### ISSUE TITLE
Upgrade Manatee issue

### ISSUE THREAD

**Issue by sodre** [zeroae/zeroae#16]
[root@headnode (us-east-1) ~]$ sdcadm up manatee -y
Finding candidate update images for the "manatee" service.
Using channel release

This update will make the following changes:
    download 1 image (74 MiB):
        image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
            (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46)
    update "manatee" service to image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d:
        (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46)
        instance "97b49e0d-9292-48ce-86e7-812e9dd80ff5" (manatee2) in server 00000000-0000-0000-0000-002590e2ac7c
        instance "853634d2-9fb8-498f-8808-129c40d25806" (manatee1) in server 00000000-0000-0000-0000-002590e2ac84
        instance "5ce31277-0614-4dcb-8e90-e05684afcd70" (manatee0) in server 00000000-0000-0000-0000-002590e29e24

Create work dir: /var/sdcadm/updates/20170108T041313Z
Downloading image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46)
Imported image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46)
Verifying manatee target version
Target version is new enough to avoid setting SAPI back to proto mode
Verifying manatee current version
manatee-adm version is >= 2.1.0. Using new commands
Updating image for SAPI service "manatee"
    service uuid: a7209247-94e5-450f-881e-93ed4865239d
get local manatee
Getting shard state from local manatee
Getting Server Information for manatee VMs
Getting SDC's moray vms from VMAPI
Getting SDC's workflow vms from VMAPI
Installing image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46) on server 00000000-0000-0000-0000-002590e29e24
Installing image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46)
Installing image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46) on server 00000000-0000-0000-0000-002590e2ac84
Installing image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46)
Installing image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46) on server 00000000-0000-0000-0000-002590e2ac7c
Installing image 6908ec3c-d2f5-11e6-ac6f-d3ab122c6f6d
    (sdc-postgres@release-20170105-20170105T031131Z-g5c63e46)
Checking manatee-adm version
Verifying full HA setup
Freezing cluster state
Reprovisioning "async" manatee
Reprovisioning 853634d2-9fb8-498f-8808-129c40d25806 VM 00000000-0000-0000-0000-002590e2ac84
Wait for manatee instance 853634d2-9fb8-498f-8808-129c40d25806 to come up
Waiting for manatee instance 853634d2-9fb8-498f-8808-129c40d25806 to come up
Waiting for manatee async to be online
Reprovisioning "sync" manatee
Reprovisioning 97b49e0d-9292-48ce-86e7-812e9dd80ff5 VM 00000000-0000-0000-0000-002590e2ac7c
Wait for manatee instance 97b49e0d-9292-48ce-86e7-812e9dd80ff5 to come up
Waiting for manatee instance 97b49e0d-9292-48ce-86e7-812e9dd80ff5 to come up
Update error: EXCEPTION: InstanceIsDownError: InstanceIsDownError: SMF svcs check failed: stdout: svc:/smartdc/mdata:execute (Joyent SDC metadata handler)
  Zone: 97b49e0d-9292-48ce-86e7-812e9dd80ff5
 Alias: manatee2
 State: maintenance since Sun Jan  8 04:16:38 2017
Reason: Start method exited with $SMF_EXIT_ERR_FATAL.
   See: http://illumos.org/msg/SMF-8000-KS
   See: /zones/97b49e0d-9292-48ce-86e7-812e9dd80ff5/root/var/svc/log/smartdc-mdata:execute.log
Impact: This service is not running.
    at /opt/smartdc/sdcadm/lib/procedures/shared.js:408:31
    at next (/opt/smartdc/sdcadm/node_modules/vasync/lib/vasync.js:201:4)
    at /opt/smartdc/sdcadm/lib/procedures/shared.js:394:36
    at /opt/smartdc/sdcadm/lib/sdcadm.js:5810:20
    at /opt/smartdc/sdcadm/node_modules/vasync/lib/vasync.js:96:5
    at /opt/smartdc/sdcadm/lib/sdcadm.js:5654:24
    at Inflight.<anonymous> (/opt/smartdc/sdcadm/node_modules/urclient/lib/ur_client.js:620:3)
    at Inflight.EventEmitter.emit (events.js:95:17)
    at URConnection._on_reply (/opt/smartdc/sdcadm/node_modules/urclient/lib/mq.js:530:9)
    at Object._onImmediate (/opt/smartdc/sdcadm/node_modules/urclient/lib/mq.js:458:11)
sdcadm up: error: SMF svcs check failed: stdout: svc:/smartdc/mdata:execute (Joyent SDC metadata handler)
  Zone: 97b49e0d-9292-48ce-86e7-812e9dd80ff5
 Alias: manatee2
 State: maintenance since Sun Jan  8 04:16:38 2017
Reason: Start method exited with $SMF_EXIT_ERR_FATAL.
   See: http://illumos.org/msg/SMF-8000-KS
   See: /zones/97b49e0d-9292-48ce-86e7-812e9dd80ff5/root/var/svc/log/smartdc-mdata:execute.log
Impact: This service is not running.

**Comment by sodre** [comment]
Rebooted head-node and upgraded again.
